name: C/C++ CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: masahikotsujita/build-containers:clang-catch-2.5.0

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir cmake-build-debug
    - name: cd
      run: cd cmake-build-debug
    - name: ls
      run: ls
    - name: ls ..
      run: ls ..
    - name: cmake
      run: cmake .. -DBUILD_TEST=true
    - name: make
      run: make
    - name: run test
      run: ./eventkittest -s
      
