name: C/C++ CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: masahikotsujita/build-containers:clang-10-catch-2.13.0-ub1804

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake .. -DBUILD_TEST=true
        make
    - name: test
      run: |
        cd cmake-build-debug
        ./eventkittest -s
      timeout-minutes: 5
